В цьому домашньому завданні ми реалізуємо логістичну регресію на `numpy`.
Ці завдання допоможуть вам ґрунтовно засвоїти основні концепції логістичної регресії та реалізувати їх на практиці 🔥

#### Завдання 1: Реалізація функції сигмоїди
1. З використанням `numpy` напишіть функцію `sigmoid(z)` для обчислення значення сигмоїди згідно з формулою:
   $$
   \sigma(z) = \frac{1}{1 + e^{-z}}
   $$
2. Використовуючи цю функцію, обчисліть значення сигмоїди для наступних даних: $ z = [-2, -1, 0, 1, 2] $. Виведіть результат обчислень.


In [1]:
import numpy as np

In [2]:
def sigmoid(z):
   return  1/(1+np.exp(-z))

In [3]:
z=np.array([-2,-1,0,1,2])

In [6]:
sigmoid_values=sigmoid(z)

In [7]:
sigmoid_values

array([0.11920292, 0.26894142, 0.5       , 0.73105858, 0.88079708])



#### Завдання 2: Реалізація функції гіпотези для логістичної регресії
1. Напишіть функцію `hypothesis(theta, X)`, яка обчислює гіпотезу для логістичної регресії, використовуючи функцію сигмоїди. Формула гіпотези:
   $$
   h_\theta(x) = \sigma(\theta^T x) = \frac{1}{1 + e^{-\theta^T x}}
   $$
2. Використайте функцію `hypothesis` для обчислення значень гіпотези для наступних даних:
   
   $\theta = [0.5, -0.5]$
   
   $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  Виведіть результат обчислень.


In [8]:
def hypothesis(theta,X):
  return sigmoid(np.dot(X, theta))

In [9]:
theta=np.array([0.5, -0.5])
X=np.array([[1, 2],
           [1,-1],
           [1,0],
           [1, 1]])

In [11]:
hypothesis_values=hypothesis(theta,X)
hypothesis_values

array([0.37754067, 0.73105858, 0.62245933, 0.5       ])

#### Завдання 3: Реалізація функції для підрахунку градієнтів фукнції втрат
1. Напишіть функцію `compute_gradient(theta, X, y)`, яка обчислює градієнти функції втрат для логістичної регресії. Формула для обчислення градієнта:
   $$
   \frac{\partial L(\theta)}{\partial \theta_j} = \frac{1}{m} \sum_{i=1}^{m} \left[ (h_\theta(x^{(i)}) - y^{(i)}) x_j^{(i)} \right]
   $$
2. Використайте функцію `compute_gradient` для обчислення градієнтів для наступних даних:

  $\theta = [0.5, -0.5]$

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Виведіть результат обчислень.

In [18]:
def compute_gradient(theta,X,y):
  m=len(y)
  h=sigmoid(np.dot(X, theta))
  gradient=(1/m)*(np.dot(X.T, (h-y)))
  return gradient

In [19]:
theta=np.array([0.5, -0.5])
X=np.array([[1, 2],
           [1,-1],
           [1,0],
           [1, 1]])
y=np.array([1, 0, 1, 0])

In [20]:
compute_gradient_values=compute_gradient(theta,X,y)
print(compute_gradient_values)

[ 0.05776464 -0.36899431]



#### Завдання 4: Реалізація повного батч градієнтного спуску

**Задача:**
1. Напишіть функцію `full_batch_gradient_descent(X, y, lr=0.1, epochs=100)`, яка реалізує алгоритм Full градієнтного спуску для логістичної регресії. Використовуйте такі формули:
   - Гіпотеза: $ h_\theta(x) = \sigma(\theta^T x) $
   - Оновлення параметрів: $ \theta_j := \theta_j - \alpha \frac{\partial L(\theta)}{\partial \theta_j} $
2. Використайте функцію `full_batch_gradient_descent` для обчислення параметрів моделі на наступних даних:

  $X = \begin{bmatrix} 1 & 2 \\ 1 & -1 \\ 1 & 0 \\ 1 & 1 \end{bmatrix}$

  $y = [1, 0, 1, 0]$

  Увага! Матриця $X$ вже має стовпець одиниць і передбачається, що це. - стовпець для intercept - параметра зсуву.

  Виведіть результат обчислень.


In [42]:
def sigmoid(z):
   return  1/(1+np.exp(-z))

def full_batch_gradient_descent(X, y, lr=0.1, epochs=100):
    m, n = X.shape
    theta = np.zeros(n)

    for _ in range(epochs):
        z = np.dot(X, theta)
        h = sigmoid(z)
        gradient = np.dot(X.T, (h - y)) / m
        theta -= lr * gradient

    return theta

In [43]:
X=np.array([[1, 2],
           [1,-1],
           [1,0],
           [1, 1]])
y=np.array([1, 0, 1, 0])

In [44]:
full_batch_gradient_descent(X, y, lr=0.1, epochs=100)

array([-0.2893693 ,  0.77655125])

#### Завдання 5. Обчислення точності моделі

1. Напишіть функцію `predict_proba(theta, X)`, яка використовує знайдені параметри $\theta$ для обчислення ймовірностей належності поточного прикладу з даних до класу $y=1$ на основі значень $\sigma(\theta^T x)$.

2. Напишіть функцію `predict(theta, X, threshold=0.5)`, яка обчислює клас з передбаченої імовірності належності екземпляра до класу 1 з порогом 0.5. Тобто якщо ймовірність менше 0.5, то передбачаємо клас 0, інакше клас 1.

3. Напишіть функцію `accuracy(y_true, y_pred)`, яка обчислює точність моделі, визначивши частку правильно передбачених класів.

  Формула метрики Accuracy:
  $$
  \text{Accuracy} = \frac{\sum_{i=1}^{m} I(\hat{{y}^{(i)}} = y^{(i)})}{m}
  $$

  де $\hat{{y}^{(i)}}$ - передбачене значення класу, $I$ - індикаторна функція (яка дорівнює 1, якщо умова виконується, і 0 - якщо ні), $m$ - кількість прикладів.

4. Обчисліть з використанням даних в завданні 4 $X$, $y$ та обчислених коефіцієнтах $\theta$ та виведіть на екран:
  - передбачені моделлю імовірності належності кожного з екземплярів в матриці `X` до класу 1
  - класи кожного екземпляра з матриці `X`
  - точність моделі.

In [52]:
def predict_proba(theta, X):
 return sigmoid(np.dot(X, theta))

In [53]:
def predict(theta, X, threshold=0.5):
  proba=predict_proba(theta,X)
  return  np.where(proba>=threshold, 1, 0)

In [54]:
def accuracy(y_true, y_pred):
  correct_predictions=np.sum(y_true==y_pred)
  total_predictions=len(y_true)
  return correct_predictions/total_predictions

In [55]:
X=np.array([[1, 2],
           [1,-1],
           [1,0],
           [1, 1]])
theta=([-0.2893693 ,  0.77655125])
y_true=np.array([1, 0, 1, 0])

In [56]:
probability=predict_proba(theta, X)
probability

array([0.77966809, 0.25617966, 0.42815828, 0.61944235])

In [57]:
y_pred=predict(theta, X, threshold=0.5)
y_pred

array([1, 0, 0, 1])

In [58]:
accuracy=accuracy(y_true, y_pred)
accuracy

0.5