### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [6]:
import random
import numpy as np

# Task 1
vector = np.random.rand(10)
vector


array([0.37479843, 0.02748626, 0.82586198, 0.44193686, 0.00436938,
       0.74662049, 0.6757293 , 0.13826635, 0.20452418, 0.72274279])

In [7]:
# Task 2
matrix=np.array([[11,14,17],
                [20,23,26],
                [29,32,35]])
matrix

array([[11, 14, 17],
       [20, 23, 26],
       [29, 32, 35]])


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [17]:
# Task 1
sum_vector= np.round(vector+10, 2)
sum_vector

array([10.37, 10.03, 10.83, 10.44, 10.  , 10.75, 10.68, 10.14, 10.2 ,
       10.72])

In [11]:
# Task 2
Matrix_multiply= matrix*2
Matrix_multiply

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [19]:
# Task 3
vector_2= np.square(sum_vector)
vector_2

array([107.5369, 100.6009, 117.2889, 108.9936, 100.    , 115.5625,
       114.0624, 102.8196, 104.04  , 114.9184])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [20]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [25]:
#Task 1
result_matrix=np.dot(B,A)
print(result_matrix )

[[0.7281 0.5202]
 [0.2034 0.2846]]


In [26]:
#Task 2
result_1=np.dot(result_matrix, C)
result_1

array([[0.5202],
       [0.2846]])

In [27]:
#Task 3
result_2=np.dot(result_matrix, D)
result_2

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [28]:
#Task 1
result_matrix_T=result_matrix.T
result_matrix_T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [29]:
#Task 2
vector_T=vector.T
vector_T

# Змін немає

array([0.37479843, 0.02748626, 0.82586198, 0.44193686, 0.00436938,
       0.74662049, 0.6757293 , 0.13826635, 0.20452418, 0.72274279])

In [38]:
vector_T.shape

(10,)

In [31]:
#Task 3
column_vector=np.expand_dims(vector, axis=1)
column_vector

#Вектор перетворився на вектор-стовпець

array([[0.37479843],
       [0.02748626],
       [0.82586198],
       [0.44193686],
       [0.00436938],
       [0.74662049],
       [0.6757293 ],
       [0.13826635],
       [0.20452418],
       [0.72274279]])

In [33]:
 #Task 4
column_vector_T=column_vector.T
column_vector_T

array([[0.37479843, 0.02748626, 0.82586198, 0.44193686, 0.00436938,
        0.74662049, 0.6757293 , 0.13826635, 0.20452418, 0.72274279]])

In [35]:
column_vector_T.shape

(1, 10)